### ISSUE TITLE
Central Computer Usage

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#18]
Central Computer currently serves no purpose, since other consoles can work on their own

**Comment by PeasantFoundry** [comment]
Central computer is an optional machine for a submarine. If there is a central computer present on a submarine, certain machines (nav console etc) will not work if it is offline. However, if there isn't a central computer on a submarine, the consoles will work as normal. To test it, add a central computer and break it. The command console should no longer be function. This system runs on tags, make sure to not remove default tags for it to function.
