### ISSUE TITLE
Some items cannot be opened in editor or without power

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#20]
You cannot open items like command console in editor or in-game if there is no power present!

**Comment by PeasantFoundry** [comment]
That sounds like the item update loop is running in the editor (it shouldn't be) and you have a central computer item present. If there is a central computer present that is offline, the command console will disable the gui for the console.

**Comment by PeasantFoundry** [comment]
Lua updates were happening in the editor. This should be fixed.
