### ISSUE TITLE
S3000D decreases it's durability in editor itself

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#24]
uuuh, idk how to show it, so here's the file
[Azimuth_Mechtrauma.zip](https://github.com/PeasantFoundry/Mechtrauma/files/10337188/Azimuth_Mechtrauma.zip)

**Comment by PeasantFoundry** [comment]
Found this issue, inverted boolean. Updates should no longer happen in the editor.
