### ISSUE TITLE
Generators and other machinery still works in editor 2: electrical boogalo

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#26]
same as always.

**Comment by PeasantFoundry** [comment]
Alright, I did more testing and I've identified the issue but I'll need to consult an expert on how to correct it. The Mechtrauma update loop only runs if the game is not pause and if a round has started. 

When you first open the sub editor a round has not started and the updates will not run. However, once you click "test" a round is started and it does not end when you return to the editor. Being in the editor does not count as being paused. So whenever you return to the editor, the updates will continue to run.

**Comment by PeasantFoundry** [comment]
Fixed. This was apparently a bug in luatrauma, Evil provided me a work around and it's been pushed.
