### ISSUE TITLE
Small Water Pumps issues

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#27]
Small water pumps always start offline even if you turned them on in editor and they also use batteries when power source is operational and provides power, causing them to fail in critical situations because batts were gone on start of round.

Steps to replicate:
1. download this sub [Humpback_Mechtrauma.zip](https://github.com/PeasantFoundry/Mechtrauma/files/10372201/Humpback_Mechtrauma.zip)
2. open it in editor and set the small water pump in right ballest to state `on` 
3. launch test
4. observe

**Comment by PeasantFoundry** [comment]
Alright, couple of things:

1. Water pump state is controlled by the electric motor, if there is an electric motor the state is 1 if there is no electric motor the state is 0.
2. The baro pump code draws grid power no matter what, if there is no grid power - it will not work. The only way I could make a backup battery work is that when you put a battery in it changes the pumps min voltage and power consumption to 0 and drains the battery, when the battery is gone it sets the power consumption and min voltage back to "normal". This results in a battery being drained no matter what when its placed in the pump. However, if the sub has no power and you put a battery in the pump, it will start to work. So you can power a pump with a battery but you cannot use one as a battery backup. If I ported the pump logic to lua I could manage the battery drain more intelligently.
3. small pump icons were not showing in the electrical view and I've fixed that issue.
