### ISSUE TITLE
Steam Power Train is completely broken

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#28]
Currently steam power train consisting from: Advanced boiler, Steam Regulator, Steam turbine and Reduction engine wont work, cause boiler doesnt transfer power to turbine.

Steps to reproduce:
1. download this sub [Kastrull_Mechtrauma.zip](https://github.com/PeasantFoundry/Mechtrauma/files/10397186/Kastrull_Mechtrauma.zip)
2. open it and start test (dont forget to use fixitems before starting cause old bug with things running in editor is still present)
3. open nav.terminal and press engine
4. go to engine room
5. observe only boiler working.

**Comment by IgRAzm** [comment]
I had noticed that in alpha the engine doesn't work if you lower performance fix values like update period from original mod values, jic maybe that's the issue.

**Comment by PeasantFoundry** [comment]
Closing for now as the advanced boiler isn't quite ready for prime time. I'll add it to the list of items to hide in the editor when I push to alpha.
