### ISSUE TITLE
Incinerator Breaks when Upgraded

### ISSUE THREAD

**Issue by MrBonesss** [PeasantFoundry/Mechtrauma#4]
Incinerator breaks when upgraded. Specifically seems to be tied to the capacity upgrade

**Comment by Goostave** [comment]
It's the super-capacity recharge speed upgrade. For now, you can add "increasesupercapacitorrechargespeed" to Incinerator's Disallowed Upgrades, in subeditor of course. If its upgrade can be disabled by default, it would better.

**Comment by PeasantFoundry** [comment]
Thanks for finding and testing this, I should be able to add this to the item prefab.
