### ISSUE TITLE
Mechtrauma Config Port Problems

### ISSUE THREAD

**Issue by PeasantFoundry** [PeasantFoundry/Mechtrauma#55]
1. Oil Base DPS is spelled phonetically and it wasn't intended to be an initial config option, instead Oil Filtration efficiency was. 
![image](https://user-images.githubusercontent.com/113934941/216780925-3c418372-4a24-4bb8-9c51-6b1e56bce225.png)

2. Oil Filtration Efficiency is not included in the settings.

3. Service life for Oil Filters is included twice:
![image](https://user-images.githubusercontent.com/113934941/216780905-e0a1416c-da1c-4012-bdca-27cf871a0724.png)
![image](https://user-images.githubusercontent.com/113934941/216780932-ea2589c4-9d99-461e-b1ad-10e044f8a407.png)

4. Float Loveliness! can we round these for display and save? 
![image](https://user-images.githubusercontent.com/113934941/216781114-f0967de8-80e9-40b8-b06a-565d4892b9fa.png)

**Comment by MapleWheels** [comment]
1. Is proper intended behaviour. #barodevmoment.
2. Oil Filtration Life is listed as "Standard Oil Filter Service Life" as that was what it's original display name was in the old config. It's just mixed up, see 3.
3. Is an error on my part, left the value empty so it autofilled to internal name.
![image](https://user-images.githubusercontent.com/16272764/216791130-e53c9521-1f95-44a3-8e77-ce6714e7883a.png)
4. Will need to be fixed in the next version of MTK. It's an issue caused by the vanilla GUI Slider.

**Comment by PeasantFoundry** [comment]
2. Not quite:

`            -- oil Filtration Efficieny / Oil Deterioration Modifier
            GUI.TextBlock(GUI.RectTransform(Vector2(1, 0.05), category.Content.RectTransform), "Oil Filtration Efficiency Rating (%)", nil, nil, GUI.Alignment.Center, true).ToolTip = 
            "This determines how long filtered oil will last in machines. A 100% efficiency rating will eliminate oil deterioration."
            -- oil Deterioration group
            local oilFiltrationEPG = GUI.LayoutGroup(GUI.RectTransform(Vector2(1.0, 0.1), category.Content.RectTransform), true, GUI.Anchor.TopLeft)
            --oil sprite
            local oilFiltrationES = ItemPrefab.GetItemPrefab("oil_can").InventoryIcon
            local image = GUI.Image(GUI.RectTransform(Vector2(0.1,1.0), oilFiltrationEPG.RectTransform), oilFiltrationES)
            image.ToolTip = "Oil Can"
            -- oil Deterioration Setting (multiplier)
            local oilFiltrationEP = GUI.NumberInput(GUI.RectTransform(Vector2(0.9,0.1), oilFiltrationEPG.RectTransform), NumberType.Float)
            oilFiltrationEP.valueStep = 1.0
            oilFiltrationEP.MinValueFloat = 1.0
            oilFiltrationEP.MaxValueFloat = 100.0
            oilFiltrationEP.FloatValue = MT.Config.oilFiltrationEP
            oilFiltrationEP.OnValueChanged = function ()
                MT.Config.oilFiltrationEP = oilFiltrationEP.FloatValue
                MT.Config.oilFiltrationM = MT.Config.oilFiltrationEP / 100
                OnChanged()
            end`

**Comment by MapleWheels** [comment]
Fixed in local dev 
![image](https://user-images.githubusercontent.com/16272764/216791300-6374869b-5dfb-4a99-8581-e1a0b30f0599.png)

**Comment by PeasantFoundry** [comment]
Alright, everything seems to be going smoothly now!
