### ISSUE TITLE
Combat Diving Suit (recycle) has the wrong icon

### ISSUE THREAD

**Issue by Krzeszny** [PeasantFoundry/Mechtrauma#62]
It's from this mod, right?
![Barotrauma_VKTwMikfxO](https://user-images.githubusercontent.com/10529134/221353878-20148720-203d-4fde-9456-8f86646b1bf1.png)

**Comment by Torca2001** [comment]
Haven't seen any incorrect icons in the unstable branch, possibly already resolved.

**Comment by TBN-MapleWheels** [comment]
Closed as not reproducible in Unstable and stale. Reopen if still observed after version 1.3 is released to Alpha.
