### ISSUE TITLE
Pumps can't get infected with ballast flora.

### ISSUE THREAD

**Issue by MajorMoth** [PeasantFoundry/Mechtrauma#65]
Pumps can't get infected with ballast flora (at least when using commands)
the "ballastflora infect" command just spits out an error if your ballast-tagged pumps are from mechtrauma.

**Comment by Torca2001** [comment]
Is this on the alpha or unstable?

**Comment by Torca2001** [comment]
On unstable ballast flora works fine, only infects pumps correctly marked with the ballast tag.
Otherwise they are not considered as valid infection points.

**Comment by Imouto-Kaede** [comment]
> Is this on the alpha or unstable?

It's on alpha.

**Comment by MajorMoth** [comment]
It's on alpha, and I fatfingered the close button, whoops.

**Comment by TBN-MapleWheels** [comment]
Closed as is fixed/not reproduced in Unstable, pushing to alpha in v1.3.
