### ISSUE TITLE
Mechtrauma is not up-to-date with 1.0 release

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#76]
Many things, like suit overrides, prices, missions and other things are not updated for 1.0

for example exosuits (fullbringer 3000 included) are not even affected by mechtrauma making them meta choice and removing entire diving suit shenanigans entirely! Also upgrade system might need to utilize new change that requires materials on top of money to upgrade hull!

Also as old guest on a show, allow me to re-introduce you:
![image](https://user-images.githubusercontent.com/42521948/229358582-7aebd8ee-7548-4414-b687-d89380b67c01.png)
da lighting
![image](https://user-images.githubusercontent.com/42521948/229358604-0b0d0338-2a6a-4b47-a32d-6d435c05b119.png)

**Comment by PeasantFoundry** [comment]
God damnit Panman! Now you've started hiding the lighting complains inside other issue reports. I feel like I've just been rick rolled.

**Comment by PeasantFoundry** [comment]
Alright, I've:

* Added an override for the exosuit that provides SCBA protection, removes pressure protection when broken, and adds support for oxygentank_fr
* Fixed a bug that allowed turrets to be placed on pump mounts
* Adjusted price of pump upgrades/installs. 
* Moved the central pump to pumps xml. 

I'll have to address the lighting issues later.
