### ISSUE TITLE
Game crashing due to pumps

### ISSUE THREAD

**Issue by Bunnymap** [PeasantFoundry/Mechtrauma#91]
Getting some weird problems that I think are related to modding toolkit and the config. Everything works fine in the sub editor, but when I host an actual game multiple things fail to work. I am using the dev version posted in the discord.

1. All Mechtrauma pumps crash the server when they are powered and try to pump water ([servercrashreport.log](https://github.com/PeasantFoundry/Mechtrauma/files/13422086/servercrashreport.log)) Base game pumps work fine.
2. The powertrain doesn't consume any durability on their parts (The machines themselves are still damaged overtime) but seemingly work fine otherwise.

Some other things are probably busted but it's kinda hard to test on account of the game constantly crashing due to pumps. All tested on base game subs with no other modded parts. Client-side Lua is installed and I'm using the lua server executable. I've reinstalled the game and my mods multiple times and have unsubscribed from everything except Lua, cs, and modding toolkit. Config is all default settings. The console is putting out several "attempt to index a nil value" errors every few seconds. I have to assume this is some kind of user error on my end, but I can't for the life of me figure it out.

**Comment by MapleWheels** [comment]
Thank you for your report and the crash log. Can you provide the full game log? I have also opened a co-issue here and will be investigating: https://github.com/MapleWheels/ModdingToolkit/issues/4

As for what I'd like from you, please kindly perform the following extra troubleshooting steps:
Delete the following folders:

`<GameInstall_Dir>/Config/`
`<GameInstall_Dir>/Publicized/`
`%localappdata%/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed`

And then reinstall `LuaCsForBarotrauma` from scratch.

This error has been seen before from other mods since the new LuaCs update due to the publicized assemblies being stale, but it may be due to ModdingToolkit, so let's see.

**Comment by Bunnymap** [comment]
[DebugConsoleLog_Client_11222023_0230.txt](https://github.com/PeasantFoundry/Mechtrauma/files/13435038/DebugConsoleLog_Client_11222023_0230.txt)
[DebugConsoleLog_Server_11222023_0229.txt](https://github.com/PeasantFoundry/Mechtrauma/files/13435039/DebugConsoleLog_Server_11222023_0229.txt)
Both server and client logs

No changes from deleting those files

**Comment by Bunnymap** [comment]
Bug is still occurring with the new workshop unstable version. Unsubscribed from all of my workshop mods and deleted them from %appdata%,  and then did a fresh install. Only things I reinstalled are lua, cs, modding toolkit, Mechtrauma Unstable, and the custom sub I'm using. Still seems to work fine in the sub editor.
[DebugConsoleLog_Client_12192023_2257.txt](https://github.com/PeasantFoundry/Mechtrauma/files/13722823/DebugConsoleLog_Client_12192023_2257.txt)
[DebugConsoleLog_Server_12192023_2257.txt](https://github.com/PeasantFoundry/Mechtrauma/files/13722824/DebugConsoleLog_Server_12192023_2257.txt)
[servercrashreport.log](https://github.com/PeasantFoundry/Mechtrauma/files/13722851/servercrashreport.log)

**Comment by PeasantFoundry** [comment]
We're currently chasing down a bug that *could* be related to this. Once we resolve it I'll be pushing a new version shortly after (that includes a bunch of other small fixes as well.)

**Comment by Bunnymap** [comment]
Recent updates seem to have fixed the issue, server works properly now.

**Comment by PeasantFoundry** [comment]
Excellent! Let us know if you run into anymore problems!
